BOX = "ubuntu/jammy64"

MEMORY = 2048
CPUS = 2

NETWORK = "private_network"

CONTROL = "acharS"
CONTROL_IP = "192.168.56.110"

Vagrant.configure("2") do |config|
	config.vm.box = BOX

	#i dnt think we need a shared folder here, maybe if we need to save state
	#config.vm.synced_folder "./shared", "/srcs"

	config.vm.provider "virtualbox" do |v|
		v.memory = MEMORY
		v.cpus = CPUS
	end

	config.vm.define CONTROL do |control|
		control.vm.hostname = CONTROL
		control.vm.network NETWORK, ip: CONTROL_IP, hostname: true
	end

	config.vm.provision "file", source: "./conf", destination: "vagrant/conf"

	config.vm.provision "shell", inline: <<-SHELL
			curl -sfL https://get.k3s.io | sh -s - server \
			--write-kubeconfig-mode=644 \
			--node-ip=#{CONTROL_IP}

			kubectl apply -f vagrant/conf/
		SHELL
end
